export {
  ANSWER_STYLE_RULES,
  FRAMING_RULES,
  LAYER_DESCRIPTIONS,
  Layer,
  MINIMUM_LAYER_FOR_TASK,
  QUESTION_COUNT_BY_SEVERITY,
  QUESTION_DEPTH_BY_LAYER,
  SIGNAL_RUBRIC,
  adaptQuestion,
  classifyGapSeverity,
  detectGaps,
  detectLayer,
  generateQuestions,
  getAllLayers,
  isUncertaintyDeclared,
  layerToNumber,
  observeSession,
  runPipeline,
  selectAnswerStyle,
  selectDepth,
  signalById,
  signalTypeToLayer,
  signalsForLayer,
  verifyAnswer,
} from "../pedagogy/index.ts";
export type {
  AnswerQuality,
  AnswerStyle,
  Confidence,
  DetectedGap,
  EvidenceSource,
  EvidenceStream,
  GapSeverity,
  GeneratedQuestion,
  LayerDetection,
  LayerDescriptor,
  ObservedSignal,
  QuestionAdaptation,
  QuestionDepth,
  SignalDefinition,
  SignalType,
  TaskType,
  VerificationAction,
  VerificationResult,
} from "../pedagogy/index.ts";
